In [10]:
%pip install geopandas
import geopandas as gpd
import pandas as pd

Requirement already satisfied: geopandas in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (0.14.4)
Requirement already satisfied: fiona>=1.8.21 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geopandas) (1.9.6)
Requirement already satisfied: numpy>=1.22 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geopandas) (1.26.2)
Requirement already satisfied: packaging in /Users/jonathan/Library/Python/3.10/lib/python/site-packages (from geopandas) (23.2)
Requirement already satisfied: pandas>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geopandas) (2.1.3)
Requirement already satisfied: pyproj>=3.3.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geopandas) (3.6.1)
Requirement already satisfied: shapely>=1.8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from geopandas) (1.8.5.post1)
Requirement already satisfied: attrs>=19.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas) (23.1.0)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas) (2023.11.17)
Requirement already satisfied: click~=8.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas) (8.1.7)
Requirement already satisfied: click-plugins>=1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from fiona>=1.8.21->geopandas) (0.7.2)
Requirement already satisfied: six in /Users/jonathan/Library/Python/3.10/lib/python/site-packages (from fiona>=1.8.21->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jonathan/Library/Python/3.10/lib/python/site-packages (from pandas>=1.4.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2023.3)
Note: you may need to restart the kernel to use updated packages.

In [11]:
mapping = {
    "CAFOs": [1, 0, 0, 0, 0, 0, 0],
    "Landfills": [0, 1, 0, 0, 0, 0, 0],
    "Mines": [0, 0, 1, 0, 0, 0, 0],
    "Negative": [0, 0, 0, 1, 0, 0, 0],
    "ProcessingPlants": [0, 0, 0, 0, 1, 0, 0],
    "RefineriesAndTerminals": [0, 0, 0, 0, 0, 1, 0],
    "WWTreatment": [0, 0, 0, 0, 0, 0, 1]
}

### Reading Test & Validation data from personal drive after download (Not executable)

### Test Data: Filtering for images labled according to the 7 METER ML labels

In [12]:
labels = ["CAFOs", "Landfills", "Mines", "Negative", "ProcessingPlants", "RefineriesAndTerminals", "WWTreatment"]

In [13]:
#read file
personal_path = 'data/train_dataset.geojson'

# Read the GeoJSON file into a GeoDataFrame
train = gpd.read_file(personal_path)
train = pd.DataFrame(train.drop(columns='geometry'))
#only keep relevant columns
train = train[["Image_Folder", "Type"]]

#init df
train_final = pd.DataFrame()

#only use files with 
for label in labels:
    label = train[train['Type'] == label]
    train_final = pd.concat([train_final, label])



train_final['Label'] = train_final['Type'].apply(lambda x: mapping[x])
train_final = train_final.drop("Type", axis=1)

train_final['Image_Folder'] = 'samples/' + train_final['Image_Folder'].astype(str)

train_final.to_csv('data/FINAL_METER_ML_test.csv', index=False)

train_final

                                        Image_Folder                  Label
0       samples/train_images/43.94827109_-93.6494963  [1, 0, 0, 0, 0, 0, 0]
3            samples/train_images/44.67296_-95.15357  [1, 0, 0, 0, 0, 0, 0]
11           samples/train_images/44.36599_-94.17547  [1, 0, 0, 0, 0, 0, 0]
12             samples/train_images/38.38138_-75.401  [1, 0, 0, 0, 0, 0, 0]
14     samples/train_images/44.26941286_-93.44801991  [1, 0, 0, 0, 0, 0, 0]
...                                              ...                    ...
85031           samples/train_images/33.694_-112.029  [0, 0, 0, 0, 0, 0, 1]
85037            samples/train_images/39.057_-96.236  [0, 0, 0, 0, 0, 0, 1]
85038            samples/train_images/37.922_-95.547  [0, 0, 0, 0, 0, 0, 1]
85056            samples/train_images/40.867_-95.572  [0, 0, 0, 0, 0, 0, 1]
85057            samples/train_images/31.711_-86.286  [0, 0, 0, 0, 0, 0, 1]

[84693 rows x 2 columns]

In [14]:
#read file
personal_path = 'data/test_dataset.geojson'

# Read the GeoJSON file into a GeoDataFrame
test = gpd.read_file(personal_path)
test = pd.DataFrame(test.drop(columns='geometry'))
#only keep relevant columns
test = test[["Image_Folder", "Type"]]

#init df
test_final = pd.DataFrame()

#only use files with 
for label in labels:
    label = test[test['Type'] == label]
    test_final = pd.concat([test_final, label])



test_final['Label'] = test_final['Type'].apply(lambda x: mapping[x])
test_final = test_final.drop("Type", axis=1)

test_final['Image_Folder'] = 'samples/' + test_final['Image_Folder'].astype(str)

test_final.to_csv('data/FINAL_METER_ML_test.csv', index=False)

test_final

                                         Image_Folder                  Label
0        samples/test_images/35.17852862_-79.99927082  [1, 0, 0, 0, 0, 0, 0]
1            samples/test_images/47.863317_-92.810639  [1, 0, 0, 0, 0, 0, 0]
2            samples/test_images/33.440833_-85.435833  [1, 0, 0, 0, 0, 0, 0]
3        samples/test_images/45.12488405_-94.24194995  [1, 0, 0, 0, 0, 0, 0]
4        samples/test_images/45.33317705_-94.50533971  [1, 0, 0, 0, 0, 0, 0]
..                                                ...                    ...
608                samples/test_images/39.902_-75.146  [0, 0, 0, 0, 0, 0, 1]
609           samples/test_images/41.36543_-72.871607  [0, 0, 0, 0, 0, 0, 1]
610  samples/test_images/37.7154645154_-122.196265866  [0, 0, 0, 0, 0, 0, 1]
614           samples/test_images/37.41881_-122.01706  [0, 0, 0, 0, 0, 0, 1]
634                 samples/test_images/35.468_-97.44  [0, 0, 0, 0, 0, 0, 1]

[990 rows x 2 columns]

### Validation data

In [15]:
#read file
personal_path = 'data/val_dataset.geojson'

# Read the GeoJSON file into a GeoDataFrame
val = gpd.read_file(personal_path)
val = pd.DataFrame(val.drop(columns='geometry'))
#only keep relevant columns
val = val[["Image_Folder", "Type"]]

#init df
val_final = pd.DataFrame()

#only use files with 
for label in labels:
    label = val[val['Type'] == label]
    val_final = pd.concat([val_final, label])



val_final['Label'] = val_final['Type'].apply(lambda x: mapping[x])
val_final = val_final.drop("Type", axis=1)

val_final['Image_Folder'] = 'samples/' + val_final['Image_Folder'].astype(str)

val_final.to_csv('data/FINAL_METER_ML_val.csv', index=False)

val_final

                                    Image_Folder                  Label
9         samples/val_images/43.89961_-92.896752  [1, 0, 0, 0, 0, 0, 0]
11   samples/val_images/45.62631288_-94.69124171  [1, 0, 0, 0, 0, 0, 0]
24   samples/val_images/34.80478667_-78.61718664  [1, 0, 0, 0, 0, 0, 0]
48         samples/val_images/46.25302_-95.09069  [1, 0, 0, 0, 0, 0, 0]
61   samples/val_images/35.54027284_-77.93292496  [1, 0, 0, 0, 0, 0, 0]
..                                           ...                    ...
479            samples/val_images/37.771_-81.153  [0, 0, 0, 0, 0, 0, 1]
487            samples/val_images/43.016_-91.169  [0, 0, 0, 0, 0, 0, 1]
490            samples/val_images/44.799_-93.431  [0, 0, 0, 0, 0, 0, 1]
501            samples/val_images/38.233_-98.308  [0, 0, 0, 0, 0, 0, 1]
508             samples/val_images/32.97_-85.075  [0, 0, 0, 0, 0, 0, 1]

[505 rows x 2 columns]

### Downsampling even further due to later decision on magnitude of dataset: max. 2000 instances per class

In [17]:
df = pd.read_csv('data/METER_ML_train_downsampled.csv')
labels = ["CAFOs","Landfills","Mines","Negative","ProcessingPlants","RefineriesAndTerminals","WWTreatment"]

df_2000 = pd.DataFrame()

for label in labels:
    df_label = df[df["Type"] == label]
    df_label = df_label.head(2000)
    df_2000 = pd.concat([df_2000, df_label], ignore_index=True)

df_2000

                                            Image_Folder         Type
0      samples/train_images/37.4846615524_-120.911345...        CAFOs
1          samples/train_images/44.156046_-95.944686.png        CAFOs
2      samples/train_images/34.97102787_-77.83076532.png        CAFOs
3       samples/train_images/43.5597697_-92.60627194.png        CAFOs
4          samples/train_images/31.761336_-85.693611.png        CAFOs
...                                                  ...          ...
13531           samples/train_images/33.522_-112.296.png  WWTreatment
13532            samples/train_images/29.196_-81.008.png  WWTreatment
13533             samples/train_images/33.18_-79.978.png  WWTreatment
13534            samples/train_images/32.578_-87.684.png  WWTreatment
13535            samples/train_images/44.416_-85.411.png  WWTreatment

[13536 rows x 2 columns]

### Reducing previously created augmentation of images due to decision for fewer training data

In [18]:
pp_aug = pd.read_csv('data/save/pp.csv')
pp_aug = pp_aug.head(170)


mines_aug = pd.read_csv('data/save/mines.csv')
mines_aug = mines_aug.head(294)

df_2000 = pd.concat([df_2000, pp_aug, mines_aug], ignore_index=True)
df_2000 = df_2000.drop('Unnamed: 0', axis=1)  # axis=1 specifies that we are dropping a column

df_2000

                                            Image_Folder   Type
0      samples/train_images/37.4846615524_-120.911345...  CAFOs
1          samples/train_images/44.156046_-95.944686.png  CAFOs
2      samples/train_images/34.97102787_-77.83076532.png  CAFOs
3       samples/train_images/43.5597697_-92.60627194.png  CAFOs
4          samples/train_images/31.761336_-85.693611.png  CAFOs
...                                                  ...    ...
13995                          augmented_final/16727.png  Mines
13996                          augmented_final/16728.png  Mines
13997                          augmented_final/16729.png  Mines
13998                          augmented_final/16730.png  Mines
13999                          augmented_final/16731.png  Mines

[14000 rows x 2 columns]

### Concat new dataset together

In [19]:
# Assuming 'df' is your existing DataFrame
df_2000['Label'] = df_2000['Type'].apply(lambda x: mapping[x])
df_2000 = df_2000.drop("Type", axis=1)
df_2000

,Image_Folder,Label
0,samples/train_images/37.4846615524_-120.911345...,"[1, 0, 0, 0, 0, 0, 0]"
1,samples/train_images/44.156046_-95.944686.png,"[1, 0, 0, 0, 0, 0, 0]"
2,samples/train_images/34.97102787_-77.83076532.png,"[1, 0, 0, 0, 0, 0, 0]"
3,samples/train_images/43.5597697_-92.60627194.png,"[1, 0, 0, 0, 0, 0, 0]"
4,samples/train_images/31.761336_-85.693611.png,"[1, 0, 0, 0, 0, 0, 0]"
...,...,...
13995,augmented_final/16727.png,"[0, 0, 1, 0, 0, 0, 0]"
13996,augmented_final/16728.png,"[0, 0, 1, 0, 0, 0, 0]"
13997,augmented_final/16729.png,"[0, 0, 1, 0, 0, 0, 0]"
13998,augmented_final/16730.png,"[0, 0, 1, 0, 0, 0, 0]"
13999,augmented_final/16731.png,"[0, 0, 1, 0, 0, 0, 0]"

In [20]:
df_2000.to_csv('data/FINAL_METER_ML_train_2000.csv', index=False)