In [20]:
import geopandas as gpd

# Read GeoJSON file
gdf = gpd.read_file('/Users/konstantinreicheneder/Desktop/METER-ML/test_dataset.geojson')

# Extract Image_Folder and Type attributes
table_data = gdf[['Image_Folder', 'Type']]

In [21]:
table_data

                                           Image_Folder      Type
0                  test_images/35.17852862_-79.99927082     CAFOs
1                      test_images/47.863317_-92.810639     CAFOs
2                      test_images/33.440833_-85.435833     CAFOs
3                  test_images/45.12488405_-94.24194995     CAFOs
4                  test_images/45.33317705_-94.50533971     CAFOs
...                                                 ...       ...
1013  test_images/47.00583316570588_-123.59481268333064  Negative
1014   test_images/49.36607075641589_-94.91771832087458  Negative
1015   test_images/44.89098222653041_-70.85399330688453  Negative
1016  test_images/42.070218299498144_-76.14613007786618  Negative
1017  test_images/26.456574005603493_-97.18876512927392  Negative

[1018 rows x 2 columns]

In [22]:
table_data['Image_Folder'] = table_data['Image_Folder'].apply(lambda x: 'samples/' + x + '.png')

/var/folders/yn/2d8nrghn6zx3z0hqpjh51dp40000gn/T/ipykernel_29002/4212222846.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  table_data['Image_Folder'] = table_data['Image_Folder'].apply(lambda x: 'samples/' + x + '.png')

In [23]:
table_data

                                           Image_Folder      Type
0      samples/test_images/35.17852862_-79.99927082.png     CAFOs
1          samples/test_images/47.863317_-92.810639.png     CAFOs
2          samples/test_images/33.440833_-85.435833.png     CAFOs
3      samples/test_images/45.12488405_-94.24194995.png     CAFOs
4      samples/test_images/45.33317705_-94.50533971.png     CAFOs
...                                                 ...       ...
1013  samples/test_images/47.00583316570588_-123.594...  Negative
1014  samples/test_images/49.36607075641589_-94.9177...  Negative
1015  samples/test_images/44.89098222653041_-70.8539...  Negative
1016  samples/test_images/42.070218299498144_-76.146...  Negative
1017  samples/test_images/26.456574005603493_-97.188...  Negative

[1018 rows x 2 columns]

In [24]:
types = ['Negative', 'ProcessingPlants', 'WWTreatment', 'Landfills', 'RefineriesAndTerminals', 'CAFOs', 'Mines']
filtered_data = table_data[table_data['Type'].isin(types)]
filtered_data

                                           Image_Folder      Type
0      samples/test_images/35.17852862_-79.99927082.png     CAFOs
1          samples/test_images/47.863317_-92.810639.png     CAFOs
2          samples/test_images/33.440833_-85.435833.png     CAFOs
3      samples/test_images/45.12488405_-94.24194995.png     CAFOs
4      samples/test_images/45.33317705_-94.50533971.png     CAFOs
...                                                 ...       ...
1013  samples/test_images/47.00583316570588_-123.594...  Negative
1014  samples/test_images/49.36607075641589_-94.9177...  Negative
1015  samples/test_images/44.89098222653041_-70.8539...  Negative
1016  samples/test_images/42.070218299498144_-76.146...  Negative
1017  samples/test_images/26.456574005603493_-97.188...  Negative

[990 rows x 2 columns]

In [25]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of LabelEncoder
encoder = LabelEncoder()

# Fit and transform the 'Type' column
filtered_data['Type_encoded'] = encoder.fit_transform(filtered_data['Type'])

# Display the updated table_data
filtered_data

/var/folders/yn/2d8nrghn6zx3z0hqpjh51dp40000gn/T/ipykernel_29002/2468586984.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data['Type_encoded'] = encoder.fit_transform(filtered_data['Type'])

,Image_Folder,Type,Type_encoded
0,samples/test_images/35.17852862_-79.99927082.png,CAFOs,0
1,samples/test_images/47.863317_-92.810639.png,CAFOs,0
2,samples/test_images/33.440833_-85.435833.png,CAFOs,0
3,samples/test_images/45.12488405_-94.24194995.png,CAFOs,0
4,samples/test_images/45.33317705_-94.50533971.png,CAFOs,0
...,...,...,...
1013,samples/test_images/47.00583316570588_-123.594...,Negative,3
1014,samples/test_images/49.36607075641589_-94.9177...,Negative,3
1015,samples/test_images/44.89098222653041_-70.8539...,Negative,3
1016,samples/test_images/42.070218299498144_-76.146...,Negative,3
1017,samples/test_images/26.456574005603493_-97.188...,Negative,3

In [26]:
type_counts = filtered_data['Type_encoded'].value_counts()
print(type_counts)

Type_encoded
3    425
4    107
6    106
1     95
5     94
0     92
2     71
Name: count, dtype: int64

In [27]:
filtered_data.to_csv('/Users/konstantinreicheneder/Desktop/METER-ML/METER_ML_test.csv', index=False)